services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: secretno
      POSTGRES_USER: postgres_user
      POSTGRES_DB: app_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks: 
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build: ./backend
    environment:
      APP_NAME: my_app_back
      DB_HOST: db
      DB_PORT: 5432
    depends_on: 
      - db
    networks: 
      - app-network


  frontend:
    build: ./frontend
    environment:
      APP_NAME: my_app_front
      BACKEND_URL: http://backend:5000
    ports: 
      - "8080:8080"
    depends_on: 
      - backend
    networks: 
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
 pgdata:
