services:
  # 1. Крашится из-за отсутствия конфига
  app1:
    image: nginx:alpine
    container_name: app1
    ports:
      - "8080:80"
    volumes:
      # ПРОБЛЕМА: Файл не существует
      # app1.conf.example добавила в директорию /config
      - ./config/app1.conf:/etc/nginx/conf.d/default.conf
    # ПРОБЛЕМА: Нет обязательной переменной ENV_REQUIRED
    # в композе прописала переменную (не совсем поняла что как и зачем. просто по примеру сработало)
    environment: 
      - CONFIG_PATH=/etc/nginx/conf.d/default.conf


  # 2. Конфликт портов - оба на 80
  app2:
    image: nginx:alpine
    container_name: app2
    ports:
      # ПРОБЛЕМА: Порт 8080 уже занят app1
      # изменила порт на 8081
      - "8081:80"

  # 3. Read-only volume где нужен write
  app3:
    image: alpine:latest
    container_name: app3
    command: sh -c "echo 'test' > /data/test.txt && cat /data/test.txt"
    volumes:
      # ПРОБЛЕМА: read-only, но пытается записать
      # удалила :ro
      - ./data:/data

  # 4. Exit code 0 при ошибке (контейнер падает, но Docker думает что всё ок)
  app4:
    image: alpine:latest
    container_name: app4
    command: sh -c "ping nonexistent-host"
    # ПРОБЛЕМА: exit 0 при ошибке - Docker не знает что проблема
    # удалила || exit 0

  # 5. Бесконечный restart loop
  app5:
    image: alpine:latest
    container_name: app5
    command: sh -c "exit 1"
    restart: no
    # ПРОБЛЕМА: restart always + сразу падает = бесконечный loop
    # в рестарт прописала no

  # 6. Отсутствует обязательная переменная
  app6:
    image: postgres:15-alpine
    container_name: app6
    # ПРОБЛЕМА: POSTGRES_PASSWORD обязательна, но не задана
    # установила переменную с паролем
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root))  
